// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: basicESP32S3_SquareLine_Project

#ifndef _BASICESP32S3_SQUARELINE_PROJECT_UI_H
#define _BASICESP32S3_SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image18;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_arduino_logo50_svg_png);    // assets/Arduino_Logo50.svg.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
